### ISSUE TITLE
ECDH-ES + HKDF-256  example

### ISSUE THREAD

**Issue by mjurczak** [TimothyClaeys/pycose#27]
Hi,
@TimothyClaeys 
First of all, great effort putting this library together 👍 

In the docs I see that ECDH-ES with direct CEK derivation is supported:
ECDH-ES + HKDF-256 | ✔️ | ECDH ES w/ HKDF - generate key directly

Is there an example or test case that I could find sample of generating Encrypt message in ECDH-ES direct CEK derivation scheme

**Comment by mjurczak** [comment]
It would be fantastic to see a snippet of code on how to do COSE_Encrypt from:
plaintext, 
recipient key (kid, x, y),
AEAD algo type

All from the inputs, ephemeral key generation, CEK derivation and message encoding and encryption. Now it is not clear for me how to use API to do that.

**Comment by TimothyClaeys** [comment]
Hi @mjurczak,
Thank you for your interest. 
I'll soon publish some examples, detailing how to use the API. I'll let you know when they are online.

**Comment by TimothyClaeys** [comment]
Hi @mjurczak, sorry for the delay, but I finally found some time to update the code. I've added an example for the ECDH ES w/ HKDF for direct key derivation (https://pycose.readthedocs.io/en/latest/examples.html#cose-encrypt)
