### ISSUE TITLE
ec2 key generate

### ISSUE THREAD

**Issue by mjurczak** [TimothyClaeys/pycose#28]
Hi,

I think that in:
https://github.com/TimothyClaeys/pycose/blob/df3e68700957df56027be580205e297e47001c19/cose/keys/ec2.py#L234-L236

the returned object does not have a curve type set:
https://github.com/TimothyClaeys/pycose/blob/df3e68700957df56027be580205e297e47001c19/cose/keys/ec2.py#L261-L266

I'm also wondering what is the need for algorithm specification here:
https://github.com/TimothyClaeys/pycose/blob/df3e68700957df56027be580205e297e47001c19/cose/keys/ec2.py#L235

Does the algorithm that the key will be used with need to be set at the key creation time?

**Comment by TimothyClaeys** [comment]
Hi @mjurczak, no that is not the case. I will update the code.

**Comment by TimothyClaeys** [comment]
Fixed in #41
