### ISSUE TITLE
Empty header encoding

### ISSUE THREAD

**Issue by mjurczak** [TimothyClaeys/pycose#29]
Hi,

I've noticed that in case of empty protected header, the resulting COSE structure header is set to an empty bstr:
https://github.com/TimothyClaeys/pycose/blob/df3e68700957df56027be580205e297e47001c19/cose/messages/cosemessage.py#L94-L97

In examples from COSE-WG empty header is an empty (0-element) byte array serialized to a bstr:
https://github.com/cose-wg/Examples/blob/master/sign1-tests/sign-pass-01.json

```
D2                                      # tag(18)
   84                                   # array(4)
      41                                # bytes(1)
         A0                             # "\xA0"
      A2                                # map(2)
         01                             # unsigned(1)
         26                             # negative(6)
         04                             # unsigned(4)
         42                             # bytes(2)
            3131                        # "11"
      54                                # bytes(20)
         546869732069732074686520636F6E74656E742E # "This is the content."
      58 40                             # bytes(64)

```

I'm not sure if both encodings are valid. What do you think?

**Comment by geonnave** [comment]
@mjurczak in fact the `A0` from the above example is an empty map (array would be `80`) inside a bstr.

It seems the implementation is correctly following [the spec](https://tools.ietf.org/html/rfc8152#section-3): 
> Senders SHOULD encode a zero-length map as a zero-length string rather than as a zero-length map (encoded as h'a0').

So I think the example SHOULD have a `40` instead of `41A0`.

**Comment by mjurczak** [comment]
It is correct indeed! Thanks to pointing to the spec :)

**Comment by TimothyClaeys** [comment]
@geonnave: Thanks for clearing that up! I wrote that code a while ago so I didn't immediately have the answer to @mjurczak question. 

@mjurczak: Btw, I'm sorry I haven't had the time to come back to you on your other questions. I'm pretty busy right now with work but I'm working on improving the API and documenting everything whenever I have time.

**Comment by TimothyClaeys** [comment]
If you agree I'll close this issue.

**Comment by mjurczak** [comment]
Yes - I think the issue can be closed.
