### ISSUE TITLE
Truncated x and y coordinates byte arrays in EC2.generate_key()

### ISSUE THREAD

**Issue by mjurczak** [TimothyClaeys/pycose#30]
I've observed that EC2.generate_key() may result in a key that is incorrecty encoded.

Notice that in the following lines the x and y byte arrays length depends on the x and y values:
https://github.com/TimothyClaeys/pycose/blob/df3e68700957df56027be580205e297e47001c19/cose/keys/ec2.py#L261-L266

If we assume that x and y are randomly distributed over the entire curve, there is a pretty high (a around 1/256 per coordinate I think) chance that a coordinate integer representation will start with at least 8 leading zero bits. In such case, the coordinate will be represented by a byte array shorter than the length of private key.

If key with leading zero bytes in either x or y is encoded using encode() method, the result does not follow the specs.
RFC8152 (13.1.1) states that EC2 points must be encoded with leading zero octets preserved. 

Sample code:
```
TRIAL_COUNT = 4096
cases = 0
for i in range(TRIAL_COUNT):
    ec2_test = EC2.generate_key(CoseAlgorithms.ECDH_ES_HKDF_256, KeyOps.DERIVE_KEY, CoseEllipticCurves.P_256)
    ec2_encoded = ec2_test.encode('x', 'y')
    if len(ec2_encoded[EC2.EC2Prm.X]) != 32 or len(ec2_encoded[EC2.EC2Prm.Y]) != 32:
        cases += 1
        print('Found a bug:')
        print(ec2_encoded)
print('Bug rate: {}'.format(cases/TRIAL_COUNT))
```

**Comment by TimothyClaeys** [comment]
I don't think this is a bug. The values of the EC key coordinates don't have to be 32 bytes long. I've added some tests to do key verification when they are encoded and decoded (https://github.com/TimothyClaeys/pycose/blob/4fbb3f67dd854255c0110a378fa9c6ee49fc98ea/tests/test_keys.py#L84)
