### ISSUE TITLE
Key parameter key_use is typed as int instead of set-of-values

### ISSUE THREAD

**Issue by BrianSipos** [TimothyClaeys/pycose#31]
The base class `CoseKey` parameter `key_ops` is currently typed in the API as `Optional[KeyOps]` when it should be something more like `Optional[Set[KeyOps]]` because the actual `COSE_Key` definition from [RFC8152](https://tools.ietf.org/html/rfc8152#section-7.1) defines it as CDDL type `[+ (tstr/int)]` and there's no meaning to duplicate values in that list.

**Comment by TimothyClaeys** [comment]
Hi @BSipos-RKF, thank you for pointing this out. I definitely made a mistake there. I am working on an updated version of the code with a redesigned API. The new version of `pycose` fixes a bunch of mistakes and inconsistencies w.r.t. the specification. I will release it soon (on the develop branch). 

I won't close this issue until the new code is released and its behavior verified.

**Comment by BrianSipos** [comment]
The current master, with new key API, works well with multiple key use values.
