### ISSUE TITLE
Adding RSA keys and algorithms

### ISSUE THREAD

**Issue by BSipos-RKF** [TimothyClaeys/pycose#33]
I really appreciate all of the effort that's gone into this library. For my purposes I want to produce some examples using RSA keypairs, and I'm comfortable hammering in an `RSA` key class in a local fork then later making a merge request.

This ticket is really to note the missing behavior and make sure there's no parallel effort.

**Comment by TimothyClaeys** [comment]
@BSipos-RKF, it would be awesome to have support for the RSA-based algorithms. As far as I know there is no ongoing effort to implement this right now. I would really appreciate a PR with suppport for RSA.

As I mentioned in the other issues (https://github.com/TimothyClaeys/pycose/issues/32#issuecomment-745160789, https://github.com/TimothyClaeys/pycose/issues/31#issuecomment-745159938), I am currently working on a major update of the code base. Most changes are related to the different `COSE_recipient` classes, the representation of the `COSE_Key`, COSE header parameters, and COSE algorithms. Maybe it would be better to wait with the RSA implementation until I've released the new code. I'm not sure how fast you need the RSA code but I plan to release the refactoring of the project soon.

**Comment by BSipos-RKF** [comment]
I'm in need of some RSA-in-COSE examples for an IETF I-D, so I'm going ahead with RSA in the current API. If it makes sense, this can be submitted as a pull request, but if it's just extra work before the updates then there's no real need. I'm less concerned about usabillity as much as getting the messages generated properly.

FYI, the differences are available now in [my fork](https://github.com/TimothyClaeys/pycose/compare/develop...BSipos-RKF:develop).

**Comment by BSipos-RKF** [comment]
Testing of the RSA algorithms adds a wrinkle that the newer OAEP and PSS mechanisms intentionally add randomness to the results, and the `cryptography` library (using openssl) seems to have no way to influence its RNG to intentionally produce deterministic output for the COSE test data.

**Comment by BSipos-RKF** [comment]
I saw the recent API rework in #41 and still want to proceed with RSA keys and algorithms. Unless I see otherwise in the short term, I will create a new (forked) branch off of current develop for this.

**Comment by manasystemizer** [comment]
Helou. I was wondering what is the future of this PR. Is there a plan to upstream it to Master? Thanks in advance and kudos for great work in this library!

**Comment by TimothyClaeys** [comment]
Hey, yes it is still in the pipeline. I've been busy with work so I've only been doing small fixes and updates on the `pycose` library, but I definitely intend to integrate this PR (hopefully soon).

**Comment by manasystemizer** [comment]
Thanks for the update. Sounds great!

**Comment by BSipos-RKF** [comment]
@TimothyClaeys it would be helpful if `develop` was a long-lived branch instead of deleting it each time it is merged into `master`. When you delete `develop` it auto-closes all merge requests into `develop` as a side-effect.

**Comment by TimothyClaeys** [comment]
Ok, sorry, I didn't realise that it was doing this. I recreated the develop branch and reopened the PR. I will resolve the conflicts.

**Comment by TimothyClaeys** [comment]
I've integrated the commits into the develop branch, if there are no issues I'll merge into master.

**Comment by BSipos-RKF** [comment]
Your edits look good and I see new unit test vectors are passing so the behavior should be good.
I haven't yet verified with actual in-situ operation but I can try this at a later time and submit any issues separately.

**Comment by TimothyClaeys** [comment]
Ok, merging in develop and closing this issue.
