### ISSUE TITLE
spurious requirement on sphinx?

### ISSUE THREAD

**Issue by jschlyter** [TimothyClaeys/pycose#38]
It seems the complete package requires Sphinx, even though it is just used for generating the documentation. As Sphinx depends on a lot of other packages, this results in a lot of unneeded dependencies for normal use.

**Comment by TimothyClaeys** [comment]
I've moved all packages required for docs building to the `dev-requirements.txt`. The `requirements.txt`, used when installing the packages through `pip`, now only contains the necessary packages for running the code.
