### ISSUE TITLE
Serializing COSE Key objects using cbor2

### ISSUE THREAD

**Issue by faune** [TimothyClaeys/pycose#39]
Hi,
Its not clear to me how to serialize a COSE Key using cbor2. I would expect something like this:

```
import cbor2
from cose import OKP, CoseAlgorithms, KeyOps

k=OKP.generate_key(algorithm=CoseAlgorithms.EDDSA, key_ops=KeyOps.VERIFY)
cbor2.dumps(k.encode())
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
_cbor2.CBOREncodeTypeError: cannot serialize type <aenum 'KTY'>

```

Im pretty sure I can "hand"-code this structure manually like this (although I would certainly prefer not to):

```
import cbor2
cbor2.dumps([{-1:6, -2:<x coordinate as bytestring>, 1: 1, 2: <kid>}]
```

Am I missing something extremely obvious here? The pycose docs also seem to indicate you can encode using cbor directly: 

From https://pycose.readthedocs.io/en/latest/cose/keys/okp.html

```
(...)
encode(*argv)
    Encode the provided key words in dictionary. The dictionary can then be encoded with CBOR.
(...)
```

**Comment by TimothyClaeys** [comment]
Thanks for your issue. This was indeed not clear. The code has been updated in #41.

Manually creating a COSE key:
```
from binascii import unhexlify

from cose.curves import P256
from cose.keys import CoseKey
from cose.keys.keyparam import KpKty, EC2KpCurve, EC2KpX, EC2KpY, KpKeyOps
from cose.keys.keytype import KtyEC2

cose_key = CoseKey.from_dict({
    KpKty: KtyEC2,
    EC2KpCurve: P256,
    EC2KpX: unhexlify(b'98F50A4FF6C05861C8860D13A638EA56C3F5AD7590BBFBF054E1C7B4D91D6280'),
    EC2KpY: unhexlify(b'F01400B089867804B8E9FC96C3932161F1934F4223069170D924B7E03BF822BB'),
    KpKeyOps: []
})

print(cose_key.encode())
```

Randomly created key:
```
from cose.keys import SymmetricKey

cose_key = SymmetricKey.generate_key(key_len=16)

print(cose_key.encode())
```

**Comment by faune** [comment]
This looks like a nice API!

But I think perhaps the encoded data is not according to [RFC8152](https://tools.ietf.org/html/rfc8152):

From [section 7](https://tools.ietf.org/html/rfc8152#section-7):
```
The CDDL grammar describing COSE_Key and COSE_KeySet is:

   COSE_Key = {
       1 => tstr / int,          ; kty
       ? 2 => bstr,              ; kid
       ? 3 => tstr / int,        ; alg
       ? 4 => [+ (tstr / int) ], ; key_ops
       ? 5 => bstr,              ; Base IV
       * label => values
   }
```

My understanding is that kty (label: 1) is always mandatory, regardless of COSE_Key, while label 2-5 is optional. The ```* label``` refers to specific key types, which in turn mandate their own labels.

I was looking into Ed25519 public keys, and according to [section 13.2](https://tools.ietf.org/html/rfc8152#section-13.2) the ```crv``` and ```x``` label is REQUIRED. So combined an COSE Key key encoded Ed25519 public key MUST include:

- kty
- crv
- x

Trying your code example above also include an empty list at the end, and I believe this list is the _optional_ key_ops from COSE_Key CDDL included above. According to CDDL encoding rules a list always have 1 or more elements, such that an empty list should always be skipped in the encoding. Current code in master seems to include this empty list:

```
$ echo a401012006215820f01400b089867804b8e9fc96c3932161f1934f4223069170d924b7e03bf822bb0480|xxd -ps -r|cbor2pretty.rb 
a4                                      # map(4)
   01                                   # unsigned(1)
   01                                   # unsigned(1)
   20                                   # negative(0)
   06                                   # unsigned(6)
   21                                   # negative(1)
   58 20                                # bytes(32)
      f01400b089867804b8e9fc96c3932161f1934f4223069170d924b7e03bf822bb # "\xF0\x14\x00\xB0\x89\x86x\x04\xB8\xE9\xFC\x96\xC3\x93!a\xF1\x93OB#\x06\x91p\xD9$\xB7\xE0;\xF8\"\xBB"
   04                                   # unsigned(4)
   80                                   # array(0)
```

I believe the last two bytes should not be present when the key_ops list is empty. And the RFC does not mandate key_ops to be present, as far as I see.

**Comment by TimothyClaeys** [comment]
You are right, I updated the COSE keys in #47. You can find new examples and explanation of the API in https://pycose.readthedocs.io/en/latest/cose/keys/symmetric.html. For now I've only had the time to update the documentation on COSE Symmetric Keys, but the others will follow shortly.

Let know what you think there are still issues with the encoding, decoding or representation of the keys.

**Comment by faune** [comment]
Looks good to me - kudos!
