### ISSUE TITLE
X509 handling broken in master

### ISSUE THREAD

**Issue by BSipos-RKF** [TimothyClaeys/pycose#45]
I opened this ticket to track changes to the `cose.extensions.x509` module for the new cose API (from #41). If this is already being worked I will wait on it. If not, I can propose changes to get the module import-able and working again.

The current first failure is using the old API:
```
ImportError: cannot import name 'CoseAlgorithms' from 'cose.algorithms'
```

**Comment by TimothyClaeys** [comment]
I did not update that extension yet and I haven't worked on it recently. You PR is definitely a welcome update. I left some remarks?
