### ISSUE TITLE
Readme: 0's instead of 1's?

### ISSUE THREAD

**Issue by yspreen** [TimothyClaeys/pycose#53]
The readme mentions Sign and Sign0 cases, while the COSE standard specifies the same differentiation (i.e. either many or 1 recipient), but calls it Sign and Sign1.

In fact the pycose docs and code seem to follow this standard as well: https://pycose.readthedocs.io/en/latest/examples.html  
Only the readme is off.

**Comment by TimothyClaeys** [comment]
Thanks for the issue, should be fixed now.
