### ISSUE TITLE
Python package dependency issue

### ISSUE THREAD

**Issue by BSipos-RKF** [TimothyClaeys/pycose#54]
When installing the current develop branch of `cose` there is now an upstream library version dependency issue. When attempting to run an application which imports `cose` I now see fatal exceptions:
```
pkg_resources.ContextualVersionConflict: (docutils 0.17 (/usr/local/lib/python3.8/site-packages), Requirement.parse('docutils<0.17'), {'sphinx-rtd-theme'})
pkg_resources.DistributionNotFound: The 'docutils<0.17' distribution was not found and is required by sphinx-rtd-theme
```
I'm installing `cose` with pip, which seems to not properly handle the two (min-version, max-version) constraints on the `docutils` package.

As a workaround I can pre-install `sphinx-rtd-theme==0.5.0` or `docutils<0.17` but it appears that the dependency from `cose` to the Sphinx tools is not really runtime, but doc building. Can the sphinx dependencies simply be moved out of the runtime `requirements.txt`?

I see that the reverse of this was done in 1103acb8fa3599a06b4b4eee704caf89857aa4a1, any reason for that?

**Comment by TimothyClaeys** [comment]
I think I moved it to the `requirements.txt` file so the automatic doc building on https://pycose.readthedocs.io/en/latest/index.html would work. I will have a look at the readthedocs manual and see if I can instruct it to use the `dev-requirements.txt`, then I can move those package out of the `requirements.txt`.

**Comment by TimothyClaeys** [comment]
I merged `develop` with `master` and uploaded it as version 0.9.dev4 to PyPi. When installing the `cose` in a fresh virtual environment with `pip` the issue seems resolved, can you confirm it also works for you?

**Comment by BSipos-RKF** [comment]
Yes, now when I `pip install cose` I see a good dependency:
```
Collecting docutils<0.17,>=0.12
```
