### ISSUE TITLE
Cannot encode custom header parameters

### ISSUE THREAD

**Issue by letmaik** [TimothyClaeys/pycose#64]
The function `_CoseAttribute.from_id()` has an argument `allow_unknown_attributes=False` but it is not possible to use this from the outside.

```
...
  File ".../site-packages/cose/messages/cosebase.py", line 50, in __init__
    CoseBase._transform_headers(self._phdr, phdr)
  File ".../site-packages/cose/messages/cosebase.py", line 159, in _transform_headers
    hp = CoseHeaderAttribute.from_id(_header_attribute)
  File ".../site-packages/cose/utils.py", line 43, in from_id
    raise CoseException(f"Unknown COSE attribute with value: [{cls.__name__} - {attribute}]")
```

**Comment by TimothyClaeys** [comment]
Thanks for reporting, this is definitely a bug. I opened a PR #65 that should fix the issue. Let me know if it works for you.

**Comment by letmaik** [comment]
Just tried it, encoding works now, though I realized decoding has the same issue.

**Comment by TimothyClaeys** [comment]
I pushed additional fixes for decoding COSE messages where the protected/unprotected headers contain unknown COSE header attributes.

**Comment by letmaik** [comment]
@TimothyClaeys All working now, thanks!
