### ISSUE TITLE
A few cases of missing `default_backend`

### ISSUE THREAD

**Issue by BrianSipos** [TimothyClaeys/pycose#66]
When running on Ubuntu 20.04, which requires an explicit `backend` argument for many `cryptographic` operations there are a few places in `cose` which do not supply the required argument and fail with an exception similar to
```
  File ".../cose/keys/ec2.py", line 100, in __init__
    public_nums = ec.derive_private_key(int.from_bytes(d, byteorder="big"),
TypeError: derive_private_key() missing 1 required positional argument: 'backend'
```
I'm going to patch up a branch which allows my uses to work, but it's not an exhaustive search for missing `backend` arguments.

**Comment by TimothyClaeys** [comment]
So only recently the `cryptography` package has made the `backend` argument optional, see (https://cryptography.io/en/latest/hazmat/backends/). I guess for backward compatibility with older versions of the `cryptography` package we should always explicitly specify the backend argument.

**Comment by TimothyClaeys** [comment]
Verified and merged.
