### ISSUE TITLE
KID incorrectly encoded as `tstr` if string is given

### ISSUE THREAD

**Issue by letmaik** [TimothyClaeys/pycose#69]
`cose.headers.KID: "foo"` produces a `tstr` value which is not according to the spec. Either a string KID is automatically encoded into a UTF-8 buffer (making it `bstr`), or an error should be thrown.

**Comment by TimothyClaeys** [comment]
Will fix this issue and push a new version to PyPi (#68).

**Comment by TimothyClaeys** [comment]
Solved in PR #70
