### ISSUE TITLE
Verifying a COSE Sign1 with public key

### ISSUE THREAD

**Issue by hgshoggins** [TimothyClaeys/pycose#72]
You probably know why I'm here: I'm trying to verify a `COSE_Sign1` message against a public key for COVID Passport verification. And I'm stuck because I don't know which methods I should use and how. So I'm asking for help here, considering I'm already able to get a `COSE_Sign1` object:
`<COSE_Sign1: [{'Algorithm': 'Es256', 'KID': b'|b\xee\xbe\x0e\xa7\xe7\t'}, {}, b'\xa4\x01dCN' ... (228 B), b'\x17\x04c\xe8\xd3' ... (64 B)]>`
I'm very bad at Python and just trying pieces of code, the usual stuff, and I'm already struggling with trying to get the value for `KID` from this `COSE_Sign1` object, then I'd like to call `verify_signature()` but I'm not sure how to import the public key (which I can retrieve, knowing the `KID`, the `Algorithm`, etc.). 
I believe I'm close, though, but any pointer to put me on the right tracks would be much welcome.

**Comment by letmaik** [comment]
@hgshoggins Is this still an issue? If so, it would help to see some code. If not, let's close this issue.

**Comment by hgshoggins** [comment]
Yes, I think it can be closed.
