### ISSUE TITLE
Invalid value for secexp, expected integer between 1 and 115792089210356248762697446949407573529996955224135760342422259061068512044369

### ISSUE THREAD

**Issue by JuliusGoddard** [TimothyClaeys/pycose#74]
I am getting this error using cose-sign1 with the ES256 algorithm.

This is an error with the single signature

I am confident that the signature is correct as it works on other programs.

Is there any way around this error?

**Comment by letmaik** [comment]
@JuliusGoddard Is this still an issue? There is not enough information here to reproduce this.

**Comment by letmaik** [comment]
Closing for now, please open a new issue with more details if this is still a problem.
