### ISSUE TITLE
"Could not find a version that staisfies the requirement cose (from versions: ) No Matching distribution found for cose"  on Raspberry Pi

### ISSUE THREAD

**Issue by lennertholvoet** [TimothyClaeys/pycose#75]
When installing cose with `pip3 install cose` on RBPi - with Python v3.10.0 I get the "Could not find a version that staisfies the requirement cose (from versions: ) No Matching distribution found for cose"

Is Python 3.10 or RBPi not supported?

**Comment by letmaik** [comment]
pycose is a pure Python package, so this shouldn't be an issue. Maybe a different PyPI index was used? If this is still an issue, let us know, otherwise I suggest closing this.

**Comment by letmaik** [comment]
Closing for now, please open a new issue with more details if this is still a problem.
