### ISSUE TITLE
How to overwrite protected attribute _enc_structure

### ISSUE THREAD

**Issue by KoljaV** [TimothyClaeys/pycose#78]
I've observed that _enc_structure is used as external AAD to authenticate the message. However _enc_structure seems to be calculated from different things including IV. But my message can be only authenticated if the "real" external AAD is used. Can I somehow overwrite _enc_structure?

**Comment by TimothyClaeys** [comment]
The `_enc_structure` is defined in the COSE specification. But it takes as parameter "real external AAD". You can specify external AAD in the constructor of a COSE message: https://github.com/TimothyClaeys/pycose/blob/897329ccbe9b2ed3d8d1bafc6c97ba50613faf25/cose/messages/cosemessage.py#L80 

This will be taken into account when computing the `_enc_structure`: https://github.com/TimothyClaeys/pycose/blob/897329ccbe9b2ed3d8d1bafc6c97ba50613faf25/cose/messages/cosemessage.py#L147

There is no API to overwrite the `_enc_structure`.

**Comment by KoljaV** [comment]
Thanks for your fast reply @TimothyClaeys ! If I understand this right:
[https://github.com/TimothyClaeys/pycose/blob/897329ccbe9b2ed3d8d1bafc6c97ba50613faf25/cose/messages/cosemessage.py#L145](url) phdr is also added to this `_enc_strucuture` .
Together with https://github.com/TimothyClaeys/pycose/blob/897329ccbe9b2ed3d8d1bafc6c97ba50613faf25/cose/messages/enccommon.py#L69 , this has the effect that the underlaying decrypt-method does not get the "real external AAD" but the _enc_structure.

**Comment by letmaik** [comment]
@KoljaV I don't think there's a problem with pycose, it's also tested against test vectors including encryption/decryption. It may be possible that the message you have was not encrypted properly.

@TimothyClaeys I think it's a bit confusing in the code that the keyword for encrypt/decrypt is named `external_aad`. The spec calls it just AAD, likely to avoid confusion with the external AAD that is part of the overall AAD. That's just a cosmetic issue though.

**Comment by letmaik** [comment]
Closing as non-issue. I opened #106 to address the naming issue.
