### ISSUE TITLE
Difference between AESCCM16128128 and AESCCM64128128

### ISSUE THREAD

**Issue by ingtommi** [TimothyClaeys/pycose#79]
I'm using this library for my thesis and I have to compare AES GCM with AES CCM, but I don't know how to choose one algorithm instead of the other. 

I'm working with nonce = 12 byte because of GCM recommendation and I saw in hazmat/cryptography that they only provide one AES CCM algorithm where nonce has to be between 7-13 byte. Why did you create more than one?

**Comment by letmaik** [comment]
pycose simply implements the COSE spec, it's not a choice of this library. Please see the IANA registry for all available algorithms and the link to the spec: https://www.iana.org/assignments/cose/cose.xhtml#algorithms.
