### ISSUE TITLE
Project setup.cfg installs sub-modules but not main package

### ISSUE THREAD

**Issue by BrianSipos** [TimothyClaeys/pycose#88]
The current `setup.cfg` configures the package search within the "pycose" directory, but that is the actual package root so the "pycose" package itself is not installed when I run `pip install .` from the checkout root.
 https://github.com/TimothyClaeys/pycose/blob/5e70f88e48d417b710f32519bf6bf70e6c4bb741/setup.cfg#L42

I think that line should be changed to `where = .` or similar to capture the whole "pycose" package.

**Comment by letmaik** [comment]
I think the `where` line should be replaced by `include`. `where` should default to `.` but that would pull in the `tests/` folder (as it has an `__init__.py`).

Following https://setuptools.pypa.io/en/latest/userguide/package_discovery.html#finding-simple-packages it should look like:

```
[options.packages.find]
include = pycose*
```

Note that the pattern is on the import names and must match both the top-level package and the subpackages, hence there's no slash or dot in there.
